environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      configuration: Debug
      platform: x86
      generator: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      configuration: Debug
      platform: x64
      generator: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      configuration: Release
      platform: x86
      generator: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      configuration: Release
      platform: x64
      generator: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Debug
      platform: x86
      generator: "Visual Studio 16 2019"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Debug
      platform: x64
      generator: "Visual Studio 16 2019"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Release
      platform: x86
      generator: "Visual Studio 16 2019"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Release
      platform: x64
      generator: "Visual Studio 16 2019"

init:
  - cmake --version
  - msbuild /version

install:
  - git submodule update --init --recursive

before_build:
  - if "%platform%"=="x86" (set generator_platform=Win32) else (set generator_platform=x64)
  - mkdir build-VS
  - pushd build-VS
  - cmake .. -G "%generator%" -A "%generator_platform%" -DCMAKE_CONFIGURATION_TYPES=%configuration%

build_script:
  - cmake --build . --config "%configuration%" -- /M
