language: cpp

dist: bionic

git:
  depth: 1
  submodules: true

matrix:
  include:

# Linux
## GCC
### GCC 7
    - name: Linux - GCC 7 - Debug
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
      env:
        - COMPILER=g++-7
        - BUILD_TYPE=Debug

    - name: Linux - GCC 7 - Release
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
      env:
        - COMPILER=g++-7
        - BUILD_TYPE=Release

### GCC 8
    - name: Linux - GCC 8 - Debug
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env:
        - COMPILER=g++-8
        - BUILD_TYPE=Debug

    - name: Linux - GCC 8 - Release
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env:
        - COMPILER=g++-8
        - BUILD_TYPE=Release

### GCC 9
    - name: Linux - GCC 9 - Debug
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - ninja-build
      env:
        - COMPILER=g++-9
        - BUILD_TYPE=Debug

    - name: Linux - GCC 9 - Release
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - ninja-build
      env:
        - COMPILER=g++-9
        - BUILD_TYPE=Release

### GCC 10
    - name: Linux - GCC 10 - Debug
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - ninja-build
      env:
        - COMPILER=g++-10
        - BUILD_TYPE=Debug

    - name: Linux - GCC 10 - Release
      arch: amd64
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - ninja-build
      env:
        - COMPILER=g++-10
        - BUILD_TYPE=Release

## Clang
### Clang 5
    - name: Linux - Clang 5 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-5.0
          packages:
            - clang-5.0
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-5.0
        - BUILD_TYPE=Debug

    - name: Linux - Clang 5 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-5.0
          packages:
            - clang-5.0
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-5.0
        - BUILD_TYPE=Release

### Clang 6
    - name: Linux - Clang 6 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-6.0
        - BUILD_TYPE=Debug

    - name: Linux - Clang 6 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-6.0
        - BUILD_TYPE=Release

### Clang 7
    - name: Linux - Clang 7 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
          packages:
            - clang-7
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-7
        - BUILD_TYPE=Debug

    - name: Linux - Clang 7 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
          packages:
            - clang-7
            - g++-7
            - ninja-build
      env:
        - COMPILER=clang++-7
        - BUILD_TYPE=Release

### Clang 8
    - name: Linux - Clang 8 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
            - g++-8
            - ninja-build
      env:
        - COMPILER=clang++-8
        - BUILD_TYPE=Debug

    - name: Linux - Clang 8 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
            - g++-8
            - ninja-build
      env:
        - COMPILER=clang++-8
        - BUILD_TYPE=Release

### Clang 9
    - name: Linux - Clang 9 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
            - g++-9
            - ninja-build
      env:
        - COMPILER=clang++-9
        - BUILD_TYPE=Debug

    - name: Linux - Clang 9 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
            - g++-9
            - ninja-build
      env:
        - COMPILER=clang++-9
        - BUILD_TYPE=Release

### Clang 10
    - name: Linux - Clang 10 - Debug
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - g++-10
            - ninja-build
      env:
        - COMPILER=clang++-10
        - BUILD_TYPE=Debug

    - name: Linux - Clang 10 - Release
      arch: amd64
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - g++-10
            - ninja-build
      env:
        - COMPILER=clang++-10
        - BUILD_TYPE=Release

script:
  - |
     if [[ (-x $(which brew)) ]]; then
       brew update
       brew install cmake ninja
       brew upgrade cmake ninja
     fi
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - if [[ "${BUILD_TYPE}" == "" ]]; then export BUILD_TYPE=Debug; fi

  - uname -a
  - cmake --version
  - ninja --version
  - ${CXX} --version

  - mkdir cmake-build
  - cd cmake-build
  - cmake .. -DCMAKE_CONFIGURATION_TYPES=${BUILD_TYPE} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DDYNAMICBITSET_BUILD_DOCS=OFF ${CMAKE_EXTRA_ARGS} -GNinja
  - cmake --build . --config ${BUILD_TYPE}
