language: cpp

dist: xenial

git:
  depth: 1
  submodules: true

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - COMPILER=g++-8

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5']
          packages: ['clang-5.0', 'g++-7']
      env:
        - COMPILER=clang++-5.0

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6']
          packages: ['clang-6.0', 'g++-7']
      env:
        - COMPILER=clang++-6.0

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-7']
          packages: ['clang-7', 'g++-7']
      env:
        - COMPILER=clang++-7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
          packages: ['clang-8', 'g++-8']
      env:
        - COMPILER=clang++-8

#    - os: osx
#      osx_image: xcode9.4
#      compiler: clang
#      env:
#        - COMPILER=clang++
#
#    - os: osx
#      osx_image: xcode10.2
#      compiler: clang
#      env:
#        - COMPILER=clang++

script:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - ${CXX} --version
  - mkdir cmake-build
  - cd cmake-build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release -- -j$(nproc)
